# Generated by Django 2.1.4 on 2019-01-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190103_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
