# Generated by Django 2.1.4 on 2019-01-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='app.Student'),
        ),
    ]
