# Generated by Django 2.1.4 on 2019-01-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190104_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='app.Grade'),
        ),
        migrations.AddField(
            model_name='course',
            name='stu',
            field=models.ManyToManyField(null=True, to='app.Student'),
        ),
    ]
